[ENG-505] feat: Add clerk login
amp-labs/cli pull request #59
Opened 2023-12-15 23:06 UTC by eberle1080

2023-12-18 19:41 UTC, laurenzlong requested changes
A few issues:
- for the deploy command, the check for the existence of the key flag should be removed, if the key flag is not present then the Clerk token should be used. If there isn't a valid Clerk token, then an error should be printed to instruct the use to either run `amp login` or to provide a key flag

- I checked out this branch and ran `task build-prod`, then the login command (note: `lamp` is my alias for the local version of the CLI)
<img width="573" alt="Screen Shot 2023-12-18 at 11 40 22 AM" src="https://github.com/amp-labs/cli/assets/3990804/c6f3133c-af3b-4c45-b8f1-6c3c664019bf">

I then cleared out my `~/Library/Application Support/Ampersand` folder and re-ran the command, got the same issue.

2023-12-18 20:06 UTC, laurenzlong commented on clerk/clerk.go
> +func GetURL(data *LoginData) string {
Can this be a more descriptive name? GetSessionURL perhaps?

2023-12-18 20:06 UTC, laurenzlong commented on clerk/clerk.go
> +func GetJwtName() string {
GetJwtFile?

2023-12-18 20:08 UTC, laurenzlong commented on request/api.go
> +		return Header{}, err
Should call `logger.Fatalf` with an error instructing the user to either run `amp login` or to provide a key flag to the command.

2023-12-19 01:28 UTC, laurenzlong commented on request/api.go
> +	logger.Fatal("no authentication method found, please either log in (amp login) or provide an API key (--key)")
```suggestion
	logger.Fatal("no authentication method found, please run 'amp login' or provide an API key through the key flag")
```

2023-12-19 01:29 UTC, laurenzlong approved these changes
Can you also remove this: https://github.com/amp-labs/cli/blob/f9e18b8bc3ad1169a22cdc1f1c603ca7075376d3/cmd/deploy.go#L32

And then double check that you can run `amp login` without an API key and it successfully deploys?

2023-12-19 22:14 UTC, eberle1080 commented
> Can you also remove this:
> 
> https://github.com/amp-labs/cli/blob/f9e18b8bc3ad1169a22cdc1f1c603ca7075376d3/cmd/deploy.go#L32
> 
> And then double check that you can run `amp login` without an API key and it successfully deploys?
> 
> https://github.com/amp-labs/testdata has example amp.yaml files you can use for deployment.

I did as you instructed, everything is working :) 

> ../bin/amp deploy -p 20c23d64-99b6-495a-8ac7-c7ae11bd91fe .
> Successfully deployed your integration readAndWriteSalesforce.

2023-12-19 22:14 UTC, merged